"""add cloudinary public id to comments

Revision ID: 023147408e55
Revises: cea63eff89ba
Create Date: 2026-09-27 05:03:53.748971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023147408e55'
down_revision: Union[str, Sequence[str], None] = 'cea63eff89ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
            'comments',
            sa.Column('cloudinary_public_id', sa.String(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'cloudinary_public_id')
    # ### end Alembic commands ###
