"""add video duration

Revision ID: 3e8c40cf970d
Revises: c9c383ebcd68
Create Date: 2026-09-19 16:24:13.030306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e8c40cf970d'
down_revision: Union[str, Sequence[str], None] = 'c9c383ebcd68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('duration', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'duration')
    # ### end Alembic commands ###
