"""Add Cloudinary public ID to videos

Revision ID: cea63eff89ba
Revises: eda4a01c1b68
Create Date: 2026-09-25 06:09:51.914570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea63eff89ba'
down_revision: Union[str, Sequence[str], None] = 'eda4a01c1b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('cloudinary_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'cloudinary_public_id')
    # ### end Alembic commands ###
