"""add video url to comments

Revision ID: eda4a01c1b68
Revises: 65dc22fc21e4
Create Date: 2026-09-23 06:57:50.593710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda4a01c1b68'
down_revision: Union[str, Sequence[str], None] = '65dc22fc21e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('video_url', sa.String(), nullable=True))
    op.alter_column('comments', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('comments', 'video_url')
    # ### end Alembic commands ###
